### ISSUE TITLE
Instants are not showing up in Home Assistant Energy

### ISSUE THREAD

**Issue by danvy** [pcourbin/ecodevices_rt2#18]
Instant sensors are not listed in Home Assistant Energy electricity grid consumption.
This prevent to use the EcoDevice RT2 as a source.
There seems to have a requirement for that https://www.home-assistant.io/more-info/statistics/

**Comment by pcourbin** [comment]
Hello @danvy,

Thank you for this issue and sorry for my delay!
Since version 2.2.3, the sensors should use the correct parameters to be “[Long-term Statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)”.
However, from what I understand: 

- Energy meters (kWh) can be used in the energy section (all "Index" in EcoRT2).
- Instantaneous power values (kW) can be used in particular in displays such as [Statistics Graphs](https://www.home-assistant.io/lovelace/statistics-graph/) 

If you have instantaneous values coming from EcoRT2, I use the "[integration](https://www.home-assistant.io/integrations/integration/)" platform (Riemann sum integral) to convert an instantaneous value into an energy meter.
For example, I have a plug connected with EnOcean to my EcoRT2, it only returns the instantaneous power value (`sensor.tv_conso`). 
To have an energy meter I use:
```yaml
- platform: integration
  source: sensor.tv_conso
  name: TV Conso Index
  unit_prefix: k
  round: 2
```
Then, `sensor.tv_conso_index` can be used as a device in the energy section of HA.
If I didn't understand the question or the answer isn't clear, please tell me!

**Comment by pcourbin** [comment]
Hello @danvy,

Can you confirm that this is resolved and that I can close the issue?

**Comment by geoninjaone** [comment]
I had the same problem, with your advice and pluging, i keep Ecodevice !!!

**Comment by pcourbin** [comment]
Thank you @geoninjaone for this feedback!
I'll take the opportunity to close this issue, hoping that it answered the original question :)

**Comment by danvy** [comment]
@pcourbin Very sorry for being so late to get back to you Pierre.
Using the integration sensor, I was able to make HA to list the RT2 in the grid consumption sensors.
An out of the box solution might be useful for everyone.
Thank you for your help :)
